spring:
  application:
    name: santander-dev-week-2024
  datasource:
    url: jdbc:h2:mem:sdw2024
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  openai:
    base-url: https://api.openai.com
    api-key: ${OPENAI_API_KEY}



